name: Advent
version: '0.1.0.0'
author: Dan Seminara
maintainer: semi225599@gmail.com
license: UnspecifiedLicense
default-extensions:
  - DeriveFoldable
  - DeriveFunctor
  - DeriveTraversable
  - LambdaCase
  - MultiWayIf
  - TupleSections
other-extensions:
  - TemplateHaskell
dependencies:
  - aeson
  - ansi-terminal
  - arithmoi
  - array
  - astar
  - attoparsec
  - base >=4.9 && <5
  - base16-bytestring
  - bytestring
  - clock
  - containers >=0.5.8.1
  - cryptohash-md5
  - deepseq
  - either
  - extra
  - hashable
  - interpolate
  - lens
  - lens-aeson
  - linear
  - megaparsec
  - memoize
  - MissingH
  - monad-loops
  - mtl
  - multiset
  - pcre-heavy
  - pointedlist
  - psqueues
  - recursion-schemes
  - ref-fd
  - sbv
  - split
  - template-haskell
  - text
  - transformers
  - unordered-containers
  - vector
executables:
  Advent:
    main: Main.hs
    source-dirs: src
    ghc-options:
      - -O2
      - -threaded
      - -Wall
      - -Wcompat
      - -Wincomplete-record-updates
      - -Wincomplete-uni-patterns
      - -Wredundant-constraints
      - -Wnoncanonical-monad-instances
build-type: Custom
custom-setup:
  dependencies:
    - base >=4.9 && <5
    - interpolate
    - text
    - Cabal
    - MissingH
    - pcre-heavy