name: Advent
version: '0.1.0.0'
author: Dan Seminara
maintainer: semi225599@gmail.com
license: UnspecifiedLicense
default-extensions:
  - DeriveFoldable
  - DeriveFunctor
  - DeriveTraversable
  - LambdaCase
  - MultiWayIf
  - TupleSections
other-extensions:
  - TemplateHaskell
ghc-options:
  - -O2
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
  - -Wnoncanonical-monad-instances
dependencies:
  - ansi-terminal
  - base >=4.9 && <5
  - clock
  - containers
  - deepseq
  - hspec
  - interpolate
  - mtl
  - text
  - split
library:
  source-dirs: src
  exposed-modules: Days
  dependencies:
    - aeson
    - arithmoi
    - array
    - astar
    - attoparsec
    - base16-bytestring
    - bytestring
    - comonad
    - containers >=0.5.8.1
    - cryptohash-md5
    - data-ordlist
    - deepseq
    - either
    - extra
    - foldl
    - hashable
    - lens
    - lens-aeson
    - linear
    - megaparsec
    - memoize
    - MissingH
    - monad-loops
    - mtl
    - parallel
    - pointedlist
    - psqueues
    - recursion-schemes
    - ref-fd
    - template-haskell
    - split
    - transformers
    - unordered-containers
    - vector
executables:
  Advent:
    main: Main.hs
    source-dirs: exes
    ghc-options:
      - -threaded
    dependencies:
      - Advent
tests:
  AdventTests:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
    dependencies:
      - Advent
build-type: Custom
custom-setup:
  dependencies:
    - base >=4.9 && <5
    - interpolate
    - text
    - Cabal
    - megaparsec
    - MissingH