name: Advent
version: '0.1.0.0'
author: Dan Seminara
maintainer: semi225599@gmail.com
license: UnspecifiedLicense
other-extensions:
  - TemplateHaskell
dependencies:
  - aeson
  - ansi-terminal
  - arithmoi
  - array
  - astar
  - async
  - attoparsec
  - base >=4.9 && <5
  - base16-bytestring
  - bytestring
  - clock
  - containers >=0.5.8.1
  - cryptohash-md5
  - data-ordlist
  - deepseq
  - either
  - errors
  - extra
  - free
  - hashable
  - hashtables
  - interpolate
  - lens
  - lens-aeson
  - megaparsec
  - MissingH
  - monad-loops
  - mtl
  - multiset
  - parallel
  - pcre-heavy
  - pcre-light
  - pipes
  - recursion-schemes
  - split
  - string-conv
  - template-haskell
  - text
  - transformers
  - unordered-containers
  - vector
executables:
  Advent:
    main: Main.hs
    source-dirs: src
    ghc-options: -O2 -threaded -Wall
build-type: Custom
custom-setup:
  dependencies:
    - base >=4.9 && <5
    - interpolate
    - text
    - Cabal
    - MissingH
    - pcre-heavy